"""
Practice: 05 File I/O
Topic: Reading and writing to text/CSV files
Goal: Log motor temperature data to a file, then read the file to find critical overheating events.
"""

import csv
import os

LOG_FILE = "motor_temp_log.csv"

def write_log(data):
    """Writes sensor data to a CSV file."""
    with open(LOG_FILE, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Timestamp", "Sensor_ID", "Temp_C", "Status"]) # Header
        for row in data:
            writer.writerow(row)
    print(f"Data successfully written to {LOG_FILE}\n")

def check_critical_temps(threshold):
    """Reads the CSV file and filters for high temperatures."""
    print(f"Scanning {LOG_FILE} for temperatures above {threshold}°C...")
    if not os.path.exists(LOG_FILE):
        print("Log file not found!")
        return

    with open(LOG_FILE, mode='r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            if float(row["Temp_C"]) > threshold:
                print(f"[ALERT] {row['Timestamp']} - {row['Sensor_ID']} critically high at {row['Temp_C']}°C!")

if __name__ == "__main__":
    # Sample data generated by our robot
    sample_data = [
        ("10:00:01", "Joint_1_Motor", 45.2, "OK"),
        ("10:00:02", "Joint_1_Motor", 55.8, "OK"),
        ("10:00:03", "Joint_1_Motor", 85.1, "WARNING"),
        ("10:00:04", "Joint_1_Motor", 92.5, "CRITICAL")
    ]
    
    write_log(sample_data)
    check_critical_temps(80.0)
